#!/bin/bash

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh Gradle startScripts/gradle
#
#       Gradle will try to find your shell on the PATH.
#
#   (2) The slashes in paths are important on Windows (for Java).
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"} # leaves trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls##*' -> '} # drop all but the target file name
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}
export APP_HOME
export APP_BASE_NAME

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='" -Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != "no" to use that value.
MAX_FD=maximum

warn() {
    if [ "$VERBOSE" = true ] ; then
        printf '%s\n' "$*" >&2
    fi
}

# Expand directories before shelling out to ls
expand_directories() {
    for file in "$@" ; do
        case $file in
          *\\ )
            printf '%s\n' "$file"
            ;;  
          * )
            ls -ld "$file" 2>\/dev\/null |
            sed -n 's|^ *[^ ]* *[^ ]* *[^ ]* *[^ ]* *[^ ]* *[^ ]* *[^ ]* *[^ ]* *\([^ ]*\) .*$|\1|p'
            ;;
        esac
    done
}

expand() {
    
    # Note: We cannot use sed -e 's|[^/]*||g' because the \1 in the sed pattern
    # would be interpreted as the first backreference, but we also have \1 in the
    # DEFAULT_JVM_OPTS.
    base="${APP_HOME#./}"
    [ "$base" = "$APP_HOME" ] && base="."
    find "$base" -maxdepth 1 -mindepth 1 -type d -name 'lib*' | sort | sed 's|^|:|' | sed -e 's|:|'"$base"/|g' | tr '\n' ' ' | sed 's| $||' | sed 's|^|:|'
}

cd "$APP_HOME" || { echo \"APP_HOME does not exist!\" >&2 ; exit 1 ; }


if [ -x "$(command -v jshell)" ] ; then
    set +e
    ( echo 'System.exit(0)' | jshell -S -J-Xmx512m )
    jshell_exit=$?
    set -e
    
    if [ $jshell_exit -eq 127 ]; then
        
        JAVA_HOME=
    fi
fi

# Increase the maximum file descriptors if we can, though if we can't then leave it to default
if ! command -v ulimit &> /dev/null ; then
    warn \"ulimit not available: ignoring -n argument\"
else
    case $( ulimit -n ) in  #(
      *unlimited*|*65536*) :;; #(
      #(
      *) ulimit -n 65536 ;;
    esac
fi

if [ "$OSTYPE" = "cygwin" ] || [ "$OSTYPE" = "msys" ] ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CP_SEP=";"
else
    CP_SEP=":"
fi

# Escape application args
for i do
    i=$( printf '%s\n' "$i" | sed "s/'/'\\\\'''/g" )
    APP_ARGS="$APP_ARGS '$i'"
done

exec "${JAVA_CMD:=java}" $DEFAULT_JVM_OPTS \$GRADLE_OPTS \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"
